### ISSUE TITLE
What happened to Onex and ToolX ?

### ISSUE THREAD

**Issue by 1RaY-1** [rajkumardusad/jitcompiler#1]
Sorry for creating this issue, it's because i have no other way to contact you

**Comment by rajkumardusad** [comment]
Hey @1RaY-1 thanks for contacting us, today morning i got an issue by someone to stop onex tool, because it is misused by many people and termux is also try to stop these kind of activities on termux so they have decided to drop support for all hacking tools for termux like metasploit, hydra etc. Here is the article https://wiki.termux.com/wiki/Hacking

So i have decided to delete the onex and tool-x, because it can be misused and its comes under the gray area its not bad but, i have deleted the both repositories. By the those tools are only for educational purpose and we have learnt a lot from them, and thanks for your valuable contribution in those tools.

**Comment by 1RaY-1** [comment]
But I don't understand, how it can be misused if only thing it does is to download/install famous pentesting tools that are legally uploaded on github and does not even each you to use it. And this tool is useful for pc as well, I personally only used it on my linux laptop.

**Comment by rajkumardusad** [comment]
Yes i know it's not bad but it's very hard to convence other people, so that's why i have deleted both tools.

**Comment by 1RaY-1** [comment]
I don't think it will help to limit users from using them (onex and toolx), because some people created onex or toolx as if it was their own repo on github and others have made forks of your repos and this forks don't die, it says here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility

But at least I suppose that now it's not your responsibility.

**Comment by rajkumardusad** [comment]
No don't try to stop anyone, and don't worry let them do whatever people want to do with those repositories. Keep learning keep growing thanks for your support bro.

**Comment by 1RaY-1** [comment]
I think this tool can be useful for cybersecurity experts and for those who just like to play with virtual machines, to safe their time and I still wanted to help improve it somehow in the future.

I'd like to continue improving onex little by little and make it available to others (if you are ok with that), so what you think is better, if you restore this repo and transfer it to me, or if i create a new repository, maybe change it's name and there I go? Maybe not to make termux angry with me, I could make this tool support Linux only.

I say all this because I'm interested in cybersec and programming and I don't used to just get rid of my projects (onex isn't my project, but i collaborated a lot). So tell me please what I better do

**Comment by rajkumardusad** [comment]
I would suggest you to because love cybersecurity, its very amazing and just learn more about it right now we have very basic knowledge about cybersecurity security. I would suggest just learn more about it and try to solve bigger problem. Yes you can use the both tool i don't have any problem with that, but if you are starting so why not something new?

**Comment by 1RaY-1** [comment]
What do you mean something new?

**Comment by rajkumardusad** [comment]
I mean some new and more powerful tool.

**Comment by 1RaY-1** [comment]
It will be difficult for me, because at the moment im not good in cybersec, that's why I prefere to take an existing tool and help to improve it

**Comment by rajkumardusad** [comment]
Okey as you wish

**Comment by 1RaY-1** [comment]
Ok,. I'll think what I will do, but can you give me an idea for the new tool that could be necessary for pentesters? If not, it's ok, i'll think about it, because there so many tools made already

**Comment by rajkumardusad** [comment]
That's great keep it up bro.

**Comment by 1RaY-1** [comment]
Last thing, if I need someone to help me with my project, maybe an advice or help with code, can I ask you for small help?

**Comment by rajkumardusad** [comment]
Yes sure why not, i will be happy to help you.

**Comment by 1RaY-1** [comment]
But how can I contact you?

**Comment by rajkumardusad** [comment]
On GitHub, linkdin, Twitter etc.

**Comment by 1RaY-1** [comment]
Okey, thanks for your attention bro
